    <form id="form1" method=post action="login.asp">

		<table cellpadding="0" cellspacing="3" border="0">
		<tr>
			<td class="smallfont"><label for="navbar_username">Login:</label></td>

			<td><input type="text" class="bginput" style="font-size: 11px" name="username" id="navbar_username" size="10" accesskey="u" tabindex="101" value="User Name" onfocus="if (this.value == 'User Name') this.value = '';" /></td>
			<td class="smallfont" colspan="2" nowrap="nowrap"><label for="cb_cookieuser_navbar"> <!-- <input type="checkbox" name="cookieuser" value="1" tabindex="103" id="cb_cookieuser_navbar" accesskey="c" />Remember Me?</label>--></td>
		</tr>
		<tr>
			<td class="smallfont"><label for="navbar_password">Password:</label></td>
			<td><input type="password" class="bginput" style="font-size: 11px" name="password" id="navbar_password" size="10" tabindex="102" /></td>
		</tr>
		<tr>
			<td colspan="2"  align=left>
        <input type="checkbox" name="remember" value="y">remember</input>&nbsp;|&nbsp;<input type="submit" class="button" value="Log in" tabindex="104" title="Enter your username and password in the boxes provided to login, or click the 'register' button to create a profile for yourself." accesskey="s" /></td>
		</tr>

		</table>
    </form>
